
  CREATE TABLE "TVC_ITGS"."T_ITGS_EMSI_MAPPING"
   (	"BH" NUMBER(8,0) NOT NULL ENABLE,
	"HPHM" VARCHAR2(32 BYTE) NOT NULL ENABLE,
	"HPZL" VARCHAR2(10 BYTE) NOT NULL ENABLE,
	"EMSI" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MATCHNUM" NUMBER(8,0) NOT NULL ENABLE,
	"UPDATETIME" DATE NOT NULL ENABLE,
	 CONSTRAINT "PK_ITGS_EMSI_MAPPING" PRIMARY KEY ("BH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS NOLOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TVC_ITGS"."T_ITGS_EMSI_MAPPING"."BH" IS '编号 主键,序列从1开始递增';
   COMMENT ON COLUMN "TVC_ITGS"."T_ITGS_EMSI_MAPPING"."HPHM" IS '号牌号码';
   COMMENT ON COLUMN "TVC_ITGS"."T_ITGS_EMSI_MAPPING"."HPZL" IS '号牌种类,种类云编号';
   COMMENT ON COLUMN "TVC_ITGS"."T_ITGS_EMSI_MAPPING"."EMSI" IS '手机串码EMSI';
   COMMENT ON COLUMN "TVC_ITGS"."T_ITGS_EMSI_MAPPING"."MATCHNUM" IS '分析间隔（默认3个月）内匹配次数';
   COMMENT ON COLUMN "TVC_ITGS"."T_ITGS_EMSI_MAPPING"."UPDATETIME" IS '更新时间';
   COMMENT ON TABLE "TVC_ITGS"."T_ITGS_EMSI_MAPPING"  IS '号牌imsi映射表';



  CREATE TABLE "TVC_ITGS"."T_ITGS_IMSI_MAPPING"
   (	"BH" NUMBER(8,0) NOT NULL ENABLE,
	"HPHM" VARCHAR2(32 BYTE) NOT NULL ENABLE,
	"HPZL" VARCHAR2(10 BYTE) NOT NULL ENABLE,
	"IMSI" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MATCHNUM" NUMBER(8,0) NOT NULL ENABLE,
	"UPDATETIME" DATE NOT NULL ENABLE,
	 CONSTRAINT "PK_ITGS_IMSI_MAPPING" PRIMARY KEY ("BH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS NOLOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TVC_ITGS"."T_ITGS_IMSI_MAPPING"."BH" IS '编号 主键,序列从1开始递增';
   COMMENT ON COLUMN "TVC_ITGS"."T_ITGS_IMSI_MAPPING"."HPHM" IS '号牌号码';
   COMMENT ON COLUMN "TVC_ITGS"."T_ITGS_IMSI_MAPPING"."HPZL" IS '号牌种类,种类云编号';
   COMMENT ON COLUMN "TVC_ITGS"."T_ITGS_IMSI_MAPPING"."IMSI" IS '手机卡串码imsi';
   COMMENT ON COLUMN "TVC_ITGS"."T_ITGS_IMSI_MAPPING"."MATCHNUM" IS '分析间隔（默认3个月）内匹配次数';
   COMMENT ON COLUMN "TVC_ITGS"."T_ITGS_IMSI_MAPPING"."UPDATETIME" IS '更新时间';
   COMMENT ON TABLE "TVC_ITGS"."T_ITGS_IMSI_MAPPING"  IS '号牌imsi映射表';
